language: python

python: 3.4

stages:
  - lint
  - test

cache:
  pip: true

before_install:
  - printf '%s\n'
           "$(cat test-requirements.txt requirements.txt)"
           > requirements.txt
jobs:
  include:
    - stage: lint
      script:
        - coala --non-interactive -V
    - stage: test
      script: python -m pytest
      after_success: codecov

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
