language: python
python:
  - 3.4

cache:
  pip: true

before_install:
  - printf '%s\n'
           "$(cat test-requirements.txt requirements.txt)"
           > requirements.txt

script:
  - coala --non-interactive -V

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

